language: rust
rust:
  - stable
#  - nightly

# matrix:
#   allow_failures:
#     - rust: nightly
#   fast_finish: true

services:
  - docker

cache: cargo

script:
  - cargo test --all

before_deploy:
  - cargo build --all --release
  - mkdir -p dist
  - cp -f target/release/revelio ./dist
  - strip dist/revelio
  - dist/revelio generate -p ./dist -u https://github.com/47ng/revelio/releases/download/${TRAVIS_TAG}/
  - cat dist/.well-known/revelio.json

deploy:
  # GitHub releases
  - provider: releases
    api_key:
      secure: uHh7mX+At04YOvSPzKeO185dHazxZPYTZFwqjVFY7WprUIHDLLFmmtRuQoOF9twWJM9RdDPNmfg0s4AEQiyQXte6AwBrOEIELcNLC/aTohTQ0ItZLXEtkzp1tFi85pI7wU52e72Zc6KzP9F2Ble4N+SLRxUfXp6o/giBSDRQ6J7FPNSFYSACVWYKY7/PiG1KJAnViDmnnF1mz3E9uD3xAnxJghGrbNZHk5/UzQes7BydGUfzfHbMcfcYWkTGnT8XaKOXnRqLhEvsE8NgVRmtA2LH5kBgURhSz5BxHs3IMLkMMfw3+W1sTQ0TU1g075bN8uRPbq/53upmQC+WAeKq0VedIyeudx7XqVpE9GUOUIyN8uEUkH+sOv5YU2d8Aw2HuJcSLD6RxW+IVrqIXLZoxc3P7CNRU2n1WyTEer4inPGfHWzU/P3qX+IL8wF5PfSS8hMEAE82xi8At0DXBLPAomr0HHsOJYTQzjTQyIjR7HbsV/DSiOI3LxqioFUnQfj5/dSB8hwnXvmNqF5c/MyII18PLN5fDOKIFBNdnyplufXdkIphN98r+GbjP1lrLalS83NwxLL9wsPf9ZFRhLvmYjes8+ese05ON/f3joLodi37O1d0ewy3GkFp5O78RWgpZAw/M2NBhmOxTGk0tD61ew9LK7Yi2fa8K+bN+dQrfEU=
    file:
      - dist/.well-known/revelio.json
      - dist/revelio
    skip_cleanup: true
    on:
      tags: true
      repo: 47ng/revelio

  # Docker image for master branch
  - provider: script
    script: scripts/deploy-docker-master.sh
    on:
      tags: false
      branch: master
      repo: 47ng/revelio

  # Docker image for tagged releases
  - provider: script
    script: scripts/deploy-docker-tagged.sh
    on:
      tags: true
      repo: 47ng/revelio

  # Publish crate on tagged releases
  - provider: cargo
    token:
      secure: fjB6CSZa28UzhG0WYvc67hPm33mhoKPD+MF7kWFQ54VWS+tbXo8QFFIyTLB/wtS/kwNK8qrvNEf+9DkfqseM1106+aA1oXS6gZ4o+oMagMX3l3Ch+00up5cWGfE/n+Iu8gUQ1k7imDJim0VkB52VCtm79vdda3JdlTZKB1/EARXTPSQOzbhHqmShBhUFIxIhdJ9r713uyLWRu4VIaUHURL8OGGHDuR7rOkaqaADsSX7JDtzMTm4FEn8zA/OfQjY9Vb0H0cdwmseo+vcn+Rhy0fZYwDiMxkfM0lCFOlRAFk7IW0IENbKUSwwquGjRv6jwp5U+8xIVFWMTeaY/LihlqqdLpUwsMC3JpLBCW4g/yLh4mAk85hA1G0ORrdG4FoW0qOPEe8htJEe8lSK1rzREBZwKf4VZ7nm9emzzH9uzb1j3YNwbfVeugG1gjfpN9WdG/El4uNgZvIMdJaU8901N30bq7tuOwULXr1+stU/IF08H/ajfVHHjBR6bFD94HPQu+4sOVc+XBDDzMgUho5xdIc2ngoSjz8N8wKx993E0GNGx1IyYdUMw69qb6rAXTHBvQihqpfXbEuCfNH8R6lMQ9dzSTnYYDxgGmM//+Aqbh3SUH65wiQVBP2n3b2s+v4d+i9RK8gRyU7HhBkaJM7i9YupUdH8iwX67VlRFmrGUgAk=
    on:
      tags: true
      repo: 47ng/revelio

env:
  global:
    - secure: mWNUuCLeCdgQjCcfxPLvhLg51HiLV3dvbU8OBq+sKizVE3Kor0tdFSiqb2lUDm5MXYQ90tDBVNg2lKkKXath5AM6wKYYZA8YgPzE8WL98+vBJVK8i29kQ0GSfLzMj4rLi0r+hkvnfRMq4hvvQV/pJ//YUVNGN7QZK0czMqrwUM0nkeeYQqRUHXlsEMWn/xbPCh8dL2VA6Vx5BRJ9SIrF0FTesz5OV3mZ3Efi2dFVA8MLcAmNA9XiW4nGRQHbiXisVmNS27Q63RwV5TU0HkVdsZj3f2FkBYXuD1demCUqm7oIjH6mAz9JhZzO1F2pY9/rqzxbNdJTGI42YxO5nMPy/Bb09ZP8LffJ7HKsZHcayFihpsteT5DCZ0SuMccTadQM4K8gS0mJJ46PK5MLK3fVXbGjvHGnqTWX6ehlqNblpGtdORbO746KOJIOwa3DEB7OH4JhfO2jhjxhIxTVHuLzkDQY+j1bu37gZhnHFYI5cA9V+Jhx4FMzeoeG1+mPT65Af3RJk8m9A2J1iOZuJxMm4zo4+ib6+uo5oeKPIfrpNqet/SWIkDJcZw8EHOE4fuFu/NjzcbO7CH1zR4ShC4OJta5tKbkrMZ9ePzUaJfOTZ194VTLtVlZ7H+KUwzqIhNBiBQ/Jpp7Sr+YmaaTau0Z76bP3cj60hE38jtUN5AK0cec=
    - secure: KrsRipFRpzwQKatiBp8dENMP6cG7jtNphdLsRLDpq1b54fKxpuKfzGS6WZoDMPXejeKAOqbby1QflCdgvbkB4+TXo1CuAJCQBORN0cdbChWpB5zIi/PFdq+Z1t71FVMBsHZkeLFgHrqF2YnxPyNZl+gOoYvxpnkHetqJfX0c7jP+XST+LlwdQzLs3cXzqc5KmdFv7sdYgzVyrRzN89TspMJmZTkTsybDm7ZBFeQTgmefGczmJoQQIrgfs/G+zOmXMqL3O28GAcaP/prhkmbNCQClP7z3Z1GPIMUOfiPLWNy54E1OLlyVO9IVDcp9FTZv8rR26vrLoh2DHa3zgrflobPtCtZmA5ZVKME/OtPNWVsF8QDgUbqYg4q6hWGhVmCJQBwqPLLHEb3hVpKzgRQTP2EDTxvOgsvRVeCT6lpglm9EVnkWzWdpgIsj/ZgxDgIEClZ9ptESoM6Bhjt3GDtF8qk5ADyjrm20FcIM/eGeCqbRhO5+vTYVrK5A1xS3gNvPNw50juGRv4pma4QxbOono+21EeLSuo9jer3zzrkbQ0z3c6Yvr/f8I0XoyM7uoStrsi8qr+zemYKYfs9emgLjKQz8iQM2pzm+pPZsoGlGYuTC6L271LMNldvkwAmlGVSBIwVLnjrtKmCA2Itxm7aeEWcS2c0m9898vnaeF+NkS8Q=
