language: rust
rust:
  - stable

script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - cargo test  --all
  - cargo build --all --release

cache: cargo

services:
  - docker

before_deploy:
  # Dogfood
  - mkdir -p dist
  - cp -f target/release/revelio ./dist
  - strip dist/revelio
  - dist/revelio generate -p ./dist -u https://github.com/47ng/revelio/releases/download/${TRAVIS_TAG}/
  - cat dist/.well-known/revelio.json
  # Docker
  - docker build -t 47ng/revelio:${TRAVIS_TAG} -t 47ng/revelio:latest .

deploy:
  provider: releases
  api_key:
    secure: uHh7mX+At04YOvSPzKeO185dHazxZPYTZFwqjVFY7WprUIHDLLFmmtRuQoOF9twWJM9RdDPNmfg0s4AEQiyQXte6AwBrOEIELcNLC/aTohTQ0ItZLXEtkzp1tFi85pI7wU52e72Zc6KzP9F2Ble4N+SLRxUfXp6o/giBSDRQ6J7FPNSFYSACVWYKY7/PiG1KJAnViDmnnF1mz3E9uD3xAnxJghGrbNZHk5/UzQes7BydGUfzfHbMcfcYWkTGnT8XaKOXnRqLhEvsE8NgVRmtA2LH5kBgURhSz5BxHs3IMLkMMfw3+W1sTQ0TU1g075bN8uRPbq/53upmQC+WAeKq0VedIyeudx7XqVpE9GUOUIyN8uEUkH+sOv5YU2d8Aw2HuJcSLD6RxW+IVrqIXLZoxc3P7CNRU2n1WyTEer4inPGfHWzU/P3qX+IL8wF5PfSS8hMEAE82xi8At0DXBLPAomr0HHsOJYTQzjTQyIjR7HbsV/DSiOI3LxqioFUnQfj5/dSB8hwnXvmNqF5c/MyII18PLN5fDOKIFBNdnyplufXdkIphN98r+GbjP1lrLalS83NwxLL9wsPf9ZFRhLvmYjes8+ese05ON/f3joLodi37O1d0ewy3GkFp5O78RWgpZAw/M2NBhmOxTGk0tD61ew9LK7Yi2fa8K+bN+dQrfEU=
  file:
    - dist/.well-known/revelio.json
    - dist/revelio
  skip_cleanup: true
  on:
    tags: true
    repo: 47ng/revelio

after_deploy:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  - docker push 47ng/revelio:${TRAVIS_TAG}
  - docker push 47ng/revelio:latest

env:
  global:
    - secure: fL9515goM1eftKYzGJLaPHq0ckjmDG3clMdka3P9vKqDVWZRqTj6BWh92SPpv5SuaeePk2xGGqYvyl80VQ04e5GoIteumYyuJCvFQmIirtM3MOx4zZLOX2KKk6e+DfdK/lYDWrxpsfxPMDbauDYJ4NpfRRDDfB/ROLwfVOi+Wv0gYvC2Y9MSCMCSPk1iRDyd4TwN4TbijdG3AuH0lg1qr4pETsdk6dfZLqjlB1wqvwQGZ+OjMSrtfWXmKHdtwBHK7zI2csr/2xv08+brKr2Dt6uureNKV3HeQcILeLTF2/CqKjM1R2XoLMV1GXjkxic0gYX2KWidUCNxd/ABWo6Y4simkvmXLxtn9XaPHWQK3FtlF6t9uTCPFbAZzXEHuk3A4rUkG1heFtF/AW+6XvZMzwNpEvhDLudowa1DTbzqYVz+SFkQTTmM+qj6iiLnziFPe/GE5UiVPlurUgBtwwH4fapSqbCQacH/otzZ6k6UDw2JtpHSNTHtUMtvT0DRNm7Kjc85Nf8K+q4aTX9KKNMbwsvatbuMRCCw49pXskaRnzj6NstbekcL7PUy0dZ9/29L1JJS/SEAOhZ892GDKGd38FYxx2x3SZcpWmHc6fn87zZRzYFVcIYIAxh9smoAayGubwulosPSlvrZtYuXmOU0c6EQi509t0rU+8NWb5i6XCk=
    - secure: QfQq9EGbNnaZFuRMwHKQFo/0sDcY5BaZkPhU1/LwUvB8k2Kz7ALG9MJdzC0BklPwVVHLyU1Zn5i6U9dyNfO/eJD+jBnVp9toZGEejNWoKHDTamXhxIud+x294U31ZfCbnNtn7BMsdwT7tZPaSrqw6+xbS5h/qra56KoP03APCcQFgeZ5ywpZg76KfaJ9b66WhuAtR9wADaao913x6qvBRa/NPwSBq7OfVYcsAwwqjzjhG4gqjEz0Bn7Z1RXaffCJCnLDr49qp/mQgZpDe56xbogfieAsvsNNOssGtdsVvChhLRhVPjFTity2l+Jb/ye1fdj8XH4Gk5a+7HSZgXtCSA188GCVBOTWgs+ACuBQH/l2IvAOfHR8xTw4In9FPpq5uWO11Vo0sEvW45UcwUgcTx4/d4YWx1HaHQv1bsyweFn8FFbiz6/s9ZoyHVdWL9ZKHndhn9P2pCWeqvd9REX4TPBY5+JfxEyaY/e2F5o0mJxdqSWOULc8+orP3ssGhocF/jtHb218l5jmpm92B5fs03jH2RDZvSkY4D8THVwtM/8H077jyUnVrU2mq/0k5V8RQUPlXT124B04vzT0ir+GogZrXDU7TsmWccaMzcpH0vr6lILkEu9J06ufXa40ASR2aULZt28viutMhKqOPdIJjGBr3YA6AgQ7SUBFCoQvirU=
