language: rust
rust:
  - stable
#  - nightly

# matrix:
#   allow_failures:
#     - rust: nightly
#   fast_finish: true

services:
  - docker

cache: cargo

script:
  - cargo test --all

before_deploy:
  - cargo build --all --release
  - mkdir -p dist
  - cp -f target/release/revelio ./dist
  - strip dist/revelio
  - dist/revelio generate -p ./dist -u https://github.com/47ng/revelio/releases/download/${TRAVIS_TAG}/
  - cat dist/.well-known/revelio.json

deploy:
  # GitHub releases
  - provider: releases
    api_key:
      secure: uHh7mX+At04YOvSPzKeO185dHazxZPYTZFwqjVFY7WprUIHDLLFmmtRuQoOF9twWJM9RdDPNmfg0s4AEQiyQXte6AwBrOEIELcNLC/aTohTQ0ItZLXEtkzp1tFi85pI7wU52e72Zc6KzP9F2Ble4N+SLRxUfXp6o/giBSDRQ6J7FPNSFYSACVWYKY7/PiG1KJAnViDmnnF1mz3E9uD3xAnxJghGrbNZHk5/UzQes7BydGUfzfHbMcfcYWkTGnT8XaKOXnRqLhEvsE8NgVRmtA2LH5kBgURhSz5BxHs3IMLkMMfw3+W1sTQ0TU1g075bN8uRPbq/53upmQC+WAeKq0VedIyeudx7XqVpE9GUOUIyN8uEUkH+sOv5YU2d8Aw2HuJcSLD6RxW+IVrqIXLZoxc3P7CNRU2n1WyTEer4inPGfHWzU/P3qX+IL8wF5PfSS8hMEAE82xi8At0DXBLPAomr0HHsOJYTQzjTQyIjR7HbsV/DSiOI3LxqioFUnQfj5/dSB8hwnXvmNqF5c/MyII18PLN5fDOKIFBNdnyplufXdkIphN98r+GbjP1lrLalS83NwxLL9wsPf9ZFRhLvmYjes8+ese05ON/f3joLodi37O1d0ewy3GkFp5O78RWgpZAw/M2NBhmOxTGk0tD61ew9LK7Yi2fa8K+bN+dQrfEU=
    file:
      - dist/.well-known/revelio.json
      - dist/revelio
    skip_cleanup: true
    on:
      tags: true
      repo: 47ng/revelio

  # Docker image for master branch
  - provider: script
    script: scripts/deploy-docker-master.sh
    on:
      tags: false
      branch: master
      repo: 47ng/revelio

  # Docker image for tagged releases
  - provider: script
    script: scripts/deploy-docker-tagged.sh
    on:
      tags: true
      repo: 47ng/revelio

  # Publish crate on tagged releases
  - provider: cargo
    token:
      secure: fjB6CSZa28UzhG0WYvc67hPm33mhoKPD+MF7kWFQ54VWS+tbXo8QFFIyTLB/wtS/kwNK8qrvNEf+9DkfqseM1106+aA1oXS6gZ4o+oMagMX3l3Ch+00up5cWGfE/n+Iu8gUQ1k7imDJim0VkB52VCtm79vdda3JdlTZKB1/EARXTPSQOzbhHqmShBhUFIxIhdJ9r713uyLWRu4VIaUHURL8OGGHDuR7rOkaqaADsSX7JDtzMTm4FEn8zA/OfQjY9Vb0H0cdwmseo+vcn+Rhy0fZYwDiMxkfM0lCFOlRAFk7IW0IENbKUSwwquGjRv6jwp5U+8xIVFWMTeaY/LihlqqdLpUwsMC3JpLBCW4g/yLh4mAk85hA1G0ORrdG4FoW0qOPEe8htJEe8lSK1rzREBZwKf4VZ7nm9emzzH9uzb1j3YNwbfVeugG1gjfpN9WdG/El4uNgZvIMdJaU8901N30bq7tuOwULXr1+stU/IF08H/ajfVHHjBR6bFD94HPQu+4sOVc+XBDDzMgUho5xdIc2ngoSjz8N8wKx993E0GNGx1IyYdUMw69qb6rAXTHBvQihqpfXbEuCfNH8R6lMQ9dzSTnYYDxgGmM//+Aqbh3SUH65wiQVBP2n3b2s+v4d+i9RK8gRyU7HhBkaJM7i9YupUdH8iwX67VlRFmrGUgAk=
    on:
      tags: true
      repo: 47ng/revelio

env:
  global:
    - secure: peMqvfiiuuPS4DY+XuMha+dciKqCjwH8OPBGjTp9x1LVR4hRGJ8/7pXB1CvmM4byDjfnF4HOf/HAfKXdyEtOLKa7nhBBSA52iECs5eMCNJ1Eoaf1aMeIQoCHtyERaOMZFyTojsgEpCxsORFLWFS18kPtcXq0oivPAdxnctLZbHTTf3eDk3suOOegqTDcPSBiDvYmRwRsfIoG/uTB9GhHnh3fWJPJL86+0J3ER2u8AfaQP4rKc6u/ztMGgN4c+TlElWAGHz+6jSDPVb8MefQcrRGoUsrHuxdxCwER0/lyhPhGS94YAwL5nvYyvINubGqISzdS0vvxhGxsqdEaPfiPgI5wlXizEmvUN0mmjK3c+VvPEZuZRsK9z9HWxOCmx2aNiVtIvXOGOLRXGXPJf4uCsokB2ISOA1+E43SXkJukRvi2gok3iYgOIsF/MydpRpV0etr+mSve6xVSBcz4vq6zt1aI1Nn2Fxo+pV5ntkyp3oCENrnokQqvtrBh5w8WfTJle3lfdaAbDxP0pZmX/IRd0WV/BN+eh98dwa/P4/CM/mllHssLVQCBJiH/4QHfj4aQAYpGQJWbIfDja5G25fcpMBTGtta3x8UVnH/IELzdbqKfVfPAV6YXKiIWfWTcpfjRAVJ7sW2Wy/NuOHwEFoBS6up9f+lusdCrEUWETRJVGmw=
    - secure: zTohKDTaQpDY8xFFrgqISwIBrZHw/3ZyCd0i4M7W5tQmk/9foG9uHAT0Fd+CEyrTCgMt9eUybO9ZfzEqcfnK/Yr9Xi5+Y8re6UuTNUlfK4VN5vOPCZfb/xdCg17agyUgn4x6LI6sn2VLEkQ+/f2d8QRywi40rucYgZO5q+y/dDm95Uhca76A/mSqiTizoJhqBALW0U3Gq9kcdEigj7j/gfxCwgx1k+EBfZvD8cfPsfhcTcUwf7Sb+KXcd2MvjSNrJP0Mi5HNH50SCXmQMjxypYSi3yliaJivyBL4ziRLMl0PNhBMfzv8yj+tvuZwGrVxI087tT2JdSUOUaakA5Lx4F6oGhPpsPwzXMX+PRqc+jtCpLXXwNKfd1c7bLK2RDjiYe4042Th9rTjuGSNlMuVZRFL3LQPiIBNj2T9i6op66rQqK6mEOeWSIW1dAlu8HM+3IV8ebcJ6df14U4xFzYNCcECA+ae3SdTPt9yp3rWROVqQd6WzVa3SM914Le6dxnFhoRSVst2AUAb6RBGaciG6qMTEtQVBY9Z45tw9ITj4iBhLovQUC78hc/MXQC7R5zfaIMD6upnpsaVnpZtWwZyHu8TRXtJqH3G7IfbBwDvazhfMosQwsAtBkSVMZV7XDfEk0UfdBA4LKPsbT+nf6nNn0PYA4OeZoZuFDk5XpDVbZM=
