language: rust
rust:
  - stable
#   - beta
#   - nightly
# matrix:
#   allow_failures:
#     - rust: nightly
#   fast_finish: true

script:
  - cargo test  --all
  - cargo build --all --release
  - cargo run --bin revelio-report --release

cache: cargo
