[workspace]
members = [
  #'revelio-server',
  'revelio-report',
  #'revelio-verify',
  'lib/niffler',
  'lib/reducto',
  #'lib/snitch',
  #'lib/accio',
]

[profile.release]
lto = true
panic = 'abort'
