version: 2

jobs:
  build:
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: circleci/rust:latest

    # environment:
    #   # Set your codecov token if your repository is private.
    #   CODECOV_TOKEN: <your-token>
    #   TZ: "/usr/share/zoneinfo/Europe/Paris"

    steps:
      - checkout
      - restore_cache:
          key: revelio-cache-v1

      - run:
          name: Install toolchains
          command: rustup toolchain install stable-x86_64-unknown-linux-gnu
      # - run:
      #     name: Check formatting
      #     command: |
      #       rustfmt --version
      #       cargo fmt -- --write-mode=diff
      - run:
          name: Stable Test
          command: rustup run stable cargo test
      # - run:
      #     name: Nightly Build
      #     command: |
      #       rustup run nightly rustc --version
      #       rustup run nightly cargo --version
      #       rustup run nightly cargo build --release --all
      #       rustup run nightly cargo run --bin revelio-report --release
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version
            rustup run stable cargo --version
            rustup run stable cargo build --release --all
            rustup run stable cargo run --bin revelio --release -- generate -p lib/ -u https://example.com
            cat ./lib/.well-known/revelio.json
      # - run:
      #     name: Upload Coverage
      #     command: ./scripts/codecov.sh
      - save_cache:
          key: project-cache
          paths:
            - '~/.cargo'
            - './target'
